// AUTOGENERATED — DO NOT EDIT BY HAND.
//
// Written by `scripts/gen-help.ts` from the shared wrapper surface contract, the
// same machine-readable file all three w6w wrappers implement. Regenerate with:
//
//     deno task gen:help
//
// Edits made here are lost on the next run, and `tests/help_test.ts` compares this
// file byte-for-byte against a fresh render — so a contract change that was not
// regenerated fails the suite instead of shipping stale help. The render is passed
// through `deno fmt` with this repo's own configuration, which is why the file
// satisfies `deno task fmt:check` like any hand-written module.
//
// Generation happens at development time on purpose: an installed `@w6w/cli` has
// no contract file beside it to read, so a runtime read would work in development
// and break for every user. Nothing under `src/` opens a JSON file.

/** One argument or flag of a command, ready to render. */
export interface HelpParam {
  /** The contract's parameter name. */
  name: string;
  /** `argument` renders under ARGUMENTS, `flag` under OPTIONS. */
  kind: "argument" | "flag";
  /** What the help line shows, e.g. `<id>` or `--format <f>`. */
  display: string;
  description: string;
  required: boolean;
}

/** One of the CLI's global flags. */
export interface HelpGlobalFlag {
  name: string;
  alias: string | null;
  type: string;
  env: string | null;
  /** What the help line shows, e.g. `-v, --version`. */
  display: string;
  description: string;
}

/** One runnable command — a leaf of the tree. */
export interface HelpCommand {
  /** The contract operation this command implements, e.g. `documents.create`. */
  operation: string;
  /** The command path below the binary, e.g. `["documents", "create"]`. */
  path: string[];
  name: string;
  /** Alternative paths that resolve to this same command. */
  aliases: string[][];
  /** The contract's summary, verbatim. */
  summary: string;
  /** The summary as it appears in a one-line COMMANDS listing. */
  short: string;
  /** The summary as it appears after the em dash in the command's own help. */
  headline: string;
  usage: string;
  /** The contract's `naming.cli` spelling, verbatim. */
  naming: string;
  /** The contract's `status` — server readiness, not wrapper completeness. */
  status: string;
  params: HelpParam[];
  examples: string[];
  notes: string[];
}

/** A group of commands, e.g. `w6w documents`. Groups are never runnable. */
export interface HelpGroup {
  name: string;
  summary: string;
  headline: string;
  usage: string;
  commands: HelpCommand[];
  /** Flags every command in the group accepts. */
  options: HelpParam[];
  examples: string[];
}

/** The whole command tree. */
export interface HelpTree {
  binary: string;
  contractVersion: string;
  tagline: string;
  usage: string;
  docsUrl: string;
  /** Commands that sit at the root because they have no siblings. */
  commands: HelpCommand[];
  groups: HelpGroup[];
  globalFlags: HelpGlobalFlag[];
  examples: string[];
}

/** One entry of the exit-code contract. */
export interface HelpExitCode {
  code: number;
  name: string;
  meaning: string;
}

/** The command tree, generated from the shared wrapper surface contract. */
export const HELP_TREE: HelpTree = {
  "binary": "w6w",
  "contractVersion": "0.4.0",
  "tagline": "command-line client for the w6w workflow platform",
  "usage": "w6w <command> [options]",
  "docsUrl": "https://w6w.dev/docs/cli",
  "commands": [
    {
      "operation": "me",
      "path": [
        "me",
      ],
      "name": "me",
      "aliases": [
        [
          "info",
        ],
      ],
      "summary": "Caller identity plus w6w component versions.",
      "short": "Caller identity plus w6w component versions",
      "headline": "caller identity plus w6w component versions",
      "usage": "w6w me [options]",
      "naming": "w6w me",
      "status": "required",
      "params": [
        {
          "name": "json",
          "kind": "flag",
          "display": "--json",
          "description": "Output raw JSON instead of a table",
          "required": false,
        },
      ],
      "examples": [
        "w6w me",
        "w6w info",
      ],
      "notes": [],
    },
    {
      "operation": "run",
      "path": [
        "run",
      ],
      "name": "run",
      "aliases": [],
      "summary":
        "Run anything addressable by URN — a connection action, a function, an endpoint or a workflow.",
      "short": "Run anything addressable by URN",
      "headline":
        "run anything addressable by URN — a connection action, a function, an endpoint or a workflow",
      "usage": "w6w run <urn> [options]",
      "naming": "w6w run <urn> [--action <a>] [--payload <json>]",
      "status": "required",
      "params": [
        {
          "name": "urn",
          "kind": "argument",
          "display": "<urn>",
          "description":
            "conn_… | wf_… | fn_… | ep_… | an alias name (see: w6w connections list, w6w workflows list)",
          "required": true,
        },
        {
          "name": "action",
          "kind": "flag",
          "display": "--action <a>",
          "description": "Action to invoke (connection URNs only)",
          "required": false,
        },
        {
          "name": "payload",
          "kind": "flag",
          "display": "--payload <json>",
          "description": "Input object, as a JSON string",
          "required": false,
        },
        {
          "name": "json",
          "kind": "flag",
          "display": "--json",
          "description": "Output raw JSON instead of a table",
          "required": false,
        },
      ],
      "examples": [
        'w6w run conn_01HQ8N --action send_email --payload \'{"to":"a@b.com"}\'',
        'w6w run wf_01HQ8N --payload \'{"email":"a@b.com"}\'',
        'w6w run --app sendgrid --action send_email --payload \'{"to":"a@b.com"}\'',
      ],
      "notes": [
        'The result is tagged by kind. A connection action and a function return their value directly; a workflow returns a run id and status "queued" and is not waited on — use "w6w workflows run <id> --wait" when you need to wait, set variables, or pass a trigger. Documents and variables are not URNs: address them with "w6w documents" and "w6w vars".',
        '--app <id> addresses a connection URN by its app instead of a conn_… id — "w6w run --app sendgrid --action send_email" in place of "w6w run conn_01HQ8N --action send_email". It resolves against `w6w connections list`: one matching connection is used outright, and none or several is a usage error (several lists every candidate with the exact command to run against it). It cannot be combined with a URN argument, and it is CLI-only — there is no equivalent in the node or python wrapper.',
      ],
    },
  ],
  "groups": [
    {
      "name": "connections",
      "summary": "Inspect connections",
      "headline": "inspect connections",
      "usage": "w6w connections <command> [options]",
      "commands": [
        {
          "operation": "connections.list",
          "path": [
            "connections",
            "list",
          ],
          "name": "list",
          "aliases": [],
          "summary": "List the caller's connections (credentials redacted).",
          "short": "List the caller's connections (credentials redacted)",
          "headline": "list the caller's connections (credentials redacted)",
          "usage": "w6w connections list [options]",
          "naming": "w6w connections list",
          "status": "required",
          "params": [
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w connections list",
            "w6w connections list --json",
          ],
          "notes": [],
        },
      ],
      "options": [],
      "examples": [
        "w6w connections list",
      ],
    },
    {
      "name": "workflows",
      "summary": "List and run workflows",
      "headline": "list and run workflows",
      "usage": "w6w workflows <command> [options]",
      "commands": [
        {
          "operation": "workflows.list",
          "path": [
            "workflows",
            "list",
          ],
          "name": "list",
          "aliases": [],
          "summary": "List the caller's workflow definitions.",
          "short": "List the caller's workflow definitions",
          "headline": "list the caller's workflow definitions",
          "usage": "w6w workflows list [options]",
          "naming": "w6w workflows list [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w workflows list",
            "w6w workflows list --project prj_01HQ8N",
          ],
          "notes": [],
        },
        {
          "operation": "workflows.run",
          "path": [
            "workflows",
            "run",
          ],
          "name": "run",
          "aliases": [],
          "summary": "Enqueue a workflow run; optionally wait for a terminal state.",
          "short": "Enqueue a workflow run; optionally wait for a terminal state",
          "headline": "enqueue a workflow run; optionally wait for a terminal state",
          "usage": "w6w workflows run <id> [options]",
          "naming": "w6w workflows run <id> [--wait] [--input <json>]",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Workflow id (see: w6w workflows list)",
              "required": true,
            },
            {
              "name": "wait",
              "kind": "flag",
              "display": "--wait",
              "description": "Wait for the run to reach a terminal state",
              "required": false,
            },
            {
              "name": "variables",
              "kind": "flag",
              "display": "--var <key=value>",
              "description": "Set a run variable (repeatable)",
              "required": false,
            },
            {
              "name": "trigger",
              "kind": "flag",
              "display": "--trigger <json>",
              "description": "Trigger payload, as a JSON string",
              "required": false,
            },
            {
              "name": "input",
              "kind": "flag",
              "display": "--input <json>",
              "description": "Run input, as a JSON string",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w workflows run wf_01HQ8N --var email=a@b.com",
            "w6w workflows run wf_01HQ8N --wait --json",
            'w6w workflows run wf_01HQ8N --input \'{"email":"a@b.com"}\'',
          ],
          "notes": [
            'Without --wait the run is queued and the command returns immediately with a run id and status "queued". With --wait the CLI returns when the run finishes or the server\'s wait window expires — a run still in progress is reported as "running", which is not an error.',
            'A run that finished with status "failed" exits 3, so --wait is usable in CI without parsing stdout.',
          ],
        },
      ],
      "options": [],
      "examples": [
        "w6w workflows list",
        "w6w workflows run wf_01HQ8N --wait",
      ],
    },
    {
      "name": "documents",
      "summary": "Create, read, update and delete documents",
      "headline": "create, read, update and delete documents",
      "usage": "w6w documents <command> [options]",
      "commands": [
        {
          "operation": "documents.list",
          "path": [
            "documents",
            "list",
          ],
          "name": "list",
          "aliases": [],
          "summary": "List the caller's documents in a project.",
          "short": "List the caller's documents in a project",
          "headline": "list the caller's documents in a project",
          "usage": "w6w documents list [options]",
          "naming": "w6w documents list [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w documents list",
            "w6w documents list --project prj_01HQ8N",
          ],
          "notes": [],
        },
        {
          "operation": "documents.get",
          "path": [
            "documents",
            "get",
          ],
          "name": "get",
          "aliases": [],
          "summary": "Fetch one document by its `doc_…` id.",
          "short": "Fetch one document by its `doc_…` id",
          "headline": "fetch one document by its `doc_…` id",
          "usage": "w6w documents get <id> [options]",
          "naming": "w6w documents get <id> [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Document id (see: w6w documents list)",
              "required": true,
            },
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w documents get doc_01HQ8N",
          ],
          "notes": [],
        },
        {
          "operation": "documents.getByKey",
          "path": [
            "documents",
            "get-by-key",
          ],
          "name": "get-by-key",
          "aliases": [],
          "summary": "Fetch one document by its human-chosen `key`.",
          "short": "Fetch one document by its human-chosen `key`",
          "headline": "fetch one document by its human-chosen `key`",
          "usage": "w6w documents get-by-key <key> [options]",
          "naming": "w6w documents get-by-key <key> [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "key",
              "kind": "argument",
              "display": "<key>",
              "description": "Document key, as chosen at creation",
              "required": true,
            },
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w documents get-by-key onboarding-email",
          ],
          "notes": [],
        },
        {
          "operation": "documents.create",
          "path": [
            "documents",
            "create",
          ],
          "name": "create",
          "aliases": [],
          "summary": "Create a document under a caller-chosen `key`.",
          "short": "Create a document under a caller-chosen `key`",
          "headline": "create a document under a caller-chosen `key`",
          "usage": "w6w documents create <key> --content <text> [options]",
          "naming":
            "w6w documents create <key> --content <text> [--format <f>] [--description <d>] [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "key",
              "kind": "argument",
              "display": "<key>",
              "description": "Document key to create (unique per project)",
              "required": true,
            },
            {
              "name": "content",
              "kind": "flag",
              "display": "--content <text>",
              "description": "Document content, as raw text",
              "required": true,
            },
            {
              "name": "format",
              "kind": "flag",
              "display": "--format <f>",
              "description": "Content format hint: text|markdown|yaml|html|json (default: text)",
              "required": false,
            },
            {
              "name": "description",
              "kind": "flag",
              "display": "--description <d>",
              "description": "Human-readable description",
              "required": false,
            },
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            'w6w documents create onboarding-email --content "Welcome aboard!" --format markdown',
          ],
          "notes": [],
        },
        {
          "operation": "documents.update",
          "path": [
            "documents",
            "update",
          ],
          "name": "update",
          "aliases": [],
          "summary": "Patch a document's content, format or description.",
          "short": "Patch a document's content, format or description",
          "headline": "patch a document's content, format or description",
          "usage": "w6w documents update <id> [options]",
          "naming":
            "w6w documents update <id> [--content <text>] [--format <f>] [--description <d>] [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Document id (see: w6w documents list)",
              "required": true,
            },
            {
              "name": "content",
              "kind": "flag",
              "display": "--content <text>",
              "description": "Document content, as raw text",
              "required": false,
            },
            {
              "name": "format",
              "kind": "flag",
              "display": "--format <f>",
              "description": "Content format hint: text|markdown|yaml|html|json (default: text)",
              "required": false,
            },
            {
              "name": "description",
              "kind": "flag",
              "display": "--description <d>",
              "description": "Human-readable description",
              "required": false,
            },
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            'w6w documents update doc_01HQ8N --content "Welcome aboard!"',
          ],
          "notes": [],
        },
        {
          "operation": "documents.delete",
          "path": [
            "documents",
            "delete",
          ],
          "name": "delete",
          "aliases": [],
          "summary": "Delete a document.",
          "short": "Delete a document",
          "headline": "delete a document",
          "usage": "w6w documents delete <id> [options]",
          "naming": "w6w documents delete <id> [--project <id>]",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Document id (see: w6w documents list)",
              "required": true,
            },
            {
              "name": "project",
              "kind": "flag",
              "display": "--project <id>",
              "description": "Project to scope to (default: the account's default project)",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w documents delete doc_01HQ8N",
          ],
          "notes": [],
        },
      ],
      "options": [
        {
          "name": "project",
          "kind": "flag",
          "display": "--project <id>",
          "description": "Project to scope to (default: the account's default project)",
          "required": false,
        },
      ],
      "examples": [
        "w6w documents list",
        "w6w documents get doc_01HQ8N",
      ],
    },
    {
      "name": "vars",
      "summary": "Create, read, update and delete variables",
      "headline": "create, read, update and delete variables",
      "usage": "w6w vars <command> [options]",
      "commands": [
        {
          "operation": "vars.list",
          "path": [
            "vars",
            "list",
          ],
          "name": "list",
          "aliases": [],
          "summary": "List the caller's typed variables.",
          "short": "List the caller's typed variables",
          "headline": "list the caller's typed variables",
          "usage": "w6w vars list [options]",
          "naming": "w6w vars list",
          "status": "required",
          "params": [
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars list",
          ],
          "notes": [],
        },
        {
          "operation": "vars.get",
          "path": [
            "vars",
            "get",
          ],
          "name": "get",
          "aliases": [],
          "summary": "Fetch one variable by its `var_…` id.",
          "short": "Fetch one variable by its `var_…` id",
          "headline": "fetch one variable by its `var_…` id",
          "usage": "w6w vars get <id> [options]",
          "naming": "w6w vars get <id>",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Variable id (see: w6w vars list)",
              "required": true,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars get var_01HQ8N",
          ],
          "notes": [],
        },
        {
          "operation": "vars.getByName",
          "path": [
            "vars",
            "get-by-name",
          ],
          "name": "get-by-name",
          "aliases": [],
          "summary": "Fetch one variable by its human-chosen `name`.",
          "short": "Fetch one variable by its human-chosen `name`",
          "headline": "fetch one variable by its human-chosen `name`",
          "usage": "w6w vars get-by-name <name> [options]",
          "naming": "w6w vars get-by-name <name>",
          "status": "required",
          "params": [
            {
              "name": "name",
              "kind": "argument",
              "display": "<name>",
              "description": "Variable name, as chosen at creation",
              "required": true,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars get-by-name greeting",
          ],
          "notes": [],
        },
        {
          "operation": "vars.create",
          "path": [
            "vars",
            "create",
          ],
          "name": "create",
          "aliases": [],
          "summary": "Create a typed variable under a caller-chosen `name`.",
          "short": "Create a typed variable under a caller-chosen `name`",
          "headline": "create a typed variable under a caller-chosen `name`",
          "usage": "w6w vars create <name> --type <t> --value <v> [options]",
          "naming": "w6w vars create <name> --type <t> --value <v> [--description <d>]",
          "status": "required",
          "params": [
            {
              "name": "name",
              "kind": "argument",
              "display": "<name>",
              "description": "Variable name to create (must match ^[a-z_][a-z0-9_]*$)",
              "required": true,
            },
            {
              "name": "type",
              "kind": "flag",
              "display": "--type <t>",
              "description": "Value type: string|number|boolean|json",
              "required": true,
            },
            {
              "name": "value",
              "kind": "flag",
              "display": "--value <v>",
              "description": "Value, validated against the variable's type",
              "required": true,
            },
            {
              "name": "description",
              "kind": "flag",
              "display": "--description <d>",
              "description": "Human-readable description",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars create greeting --type string --value hello",
          ],
          "notes": [],
        },
        {
          "operation": "vars.update",
          "path": [
            "vars",
            "update",
          ],
          "name": "update",
          "aliases": [],
          "summary": "Patch a variable's type, value or description.",
          "short": "Patch a variable's type, value or description",
          "headline": "patch a variable's type, value or description",
          "usage": "w6w vars update <id> [options]",
          "naming": "w6w vars update <id> [--type <t>] [--value <v>] [--description <d>]",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Variable id (see: w6w vars list)",
              "required": true,
            },
            {
              "name": "type",
              "kind": "flag",
              "display": "--type <t>",
              "description": "Value type: string|number|boolean|json",
              "required": false,
            },
            {
              "name": "value",
              "kind": "flag",
              "display": "--value <v>",
              "description": "Value, validated against the variable's type",
              "required": false,
            },
            {
              "name": "description",
              "kind": "flag",
              "display": "--description <d>",
              "description": "Human-readable description",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars update var_01HQ8N --value goodbye",
          ],
          "notes": [],
        },
        {
          "operation": "vars.delete",
          "path": [
            "vars",
            "delete",
          ],
          "name": "delete",
          "aliases": [],
          "summary": "Delete a variable.",
          "short": "Delete a variable",
          "headline": "delete a variable",
          "usage": "w6w vars delete <id> [options]",
          "naming": "w6w vars delete <id>",
          "status": "required",
          "params": [
            {
              "name": "id",
              "kind": "argument",
              "display": "<id>",
              "description": "Variable id (see: w6w vars list)",
              "required": true,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w vars delete var_01HQ8N",
          ],
          "notes": [],
        },
      ],
      "options": [],
      "examples": [
        "w6w vars list",
        "w6w vars create greeting --type string --value hello",
      ],
    },
    {
      "name": "functions",
      "summary": "Run functions by key or id",
      "headline": "run functions by key or id",
      "usage": "w6w functions <command> [options]",
      "commands": [
        {
          "operation": "functions.run",
          "path": [
            "functions",
            "run",
          ],
          "name": "run",
          "aliases": [],
          "summary": "Run one Function by its key (or id) and return its output.",
          "short": "Run one Function by its key (or id) and return its output",
          "headline": "run one Function by its key (or id) and return its output",
          "usage": "w6w functions run --id-or-key <value> [options]",
          "naming": "w6w functions run <name> [--payload <json>]",
          "status": "required",
          "params": [
            {
              "name": "idOrKey",
              "kind": "flag",
              "display": "--id-or-key <value>",
              "description": "Function key or id (e.g. send-email)",
              "required": true,
            },
            {
              "name": "inputs",
              "kind": "flag",
              "display": "--inputs <value>",
              "description": "The Function's inputs, as a JSON object",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w functions run send-email",
            'w6w functions run send-email --payload \'{"to":"a@b.com"}\'',
            "w6w functions run fn_01HQ8N --json",
          ],
          "notes": [],
        },
      ],
      "options": [
        {
          "name": "idOrKey",
          "kind": "flag",
          "display": "--id-or-key <value>",
          "description": "Function key or id (e.g. send-email)",
          "required": true,
        },
        {
          "name": "inputs",
          "kind": "flag",
          "display": "--inputs <value>",
          "description": "The Function's inputs, as a JSON object",
          "required": false,
        },
      ],
      "examples": [
        "w6w functions run send-email",
      ],
    },
    {
      "name": "endpoints",
      "summary": "Run endpoints by key or id",
      "headline": "run endpoints by key or id",
      "usage": "w6w endpoints <command> [options]",
      "commands": [
        {
          "operation": "endpoints.run",
          "path": [
            "endpoints",
            "run",
          ],
          "name": "run",
          "aliases": [],
          "summary":
            "Run one Endpoint by its key (or id); the envelope's kind says which arm answered.",
          "short":
            "Run one Endpoint by its key (or id); the envelope's kind says which arm answered",
          "headline":
            "run one Endpoint by its key (or id); the envelope's kind says which arm answered",
          "usage": "w6w endpoints run --id-or-key <value> [options]",
          "naming": "w6w endpoints run <name> [--payload <json>]",
          "status": "required",
          "params": [
            {
              "name": "idOrKey",
              "kind": "flag",
              "display": "--id-or-key <value>",
              "description": "Endpoint key or id (e.g. send-email)",
              "required": true,
            },
            {
              "name": "input",
              "kind": "flag",
              "display": "--input <value>",
              "description": "The Endpoint's input, as a JSON object",
              "required": false,
            },
            {
              "name": "json",
              "kind": "flag",
              "display": "--json",
              "description": "Output raw JSON instead of a table",
              "required": false,
            },
          ],
          "examples": [
            "w6w endpoints run send-email",
            'w6w endpoints run send-email --payload \'{"to":"a@b.com"}\'',
          ],
          "notes": [],
        },
      ],
      "options": [
        {
          "name": "idOrKey",
          "kind": "flag",
          "display": "--id-or-key <value>",
          "description": "Endpoint key or id (e.g. send-email)",
          "required": true,
        },
        {
          "name": "input",
          "kind": "flag",
          "display": "--input <value>",
          "description": "The Endpoint's input, as a JSON object",
          "required": false,
        },
      ],
      "examples": [
        "w6w endpoints run send-email",
      ],
    },
  ],
  "globalFlags": [
    {
      "name": "--base-url",
      "alias": null,
      "type": "string",
      "env": "W6W_BASE_URL",
      "display": "--base-url <url>",
      "description": "API base URL (env: W6W_BASE_URL)",
    },
    {
      "name": "--token",
      "alias": null,
      "type": "string",
      "env": "W6W_TOKEN",
      "display": "--token <token>",
      "description": "API token (env: W6W_TOKEN)",
    },
    {
      "name": "--json",
      "alias": null,
      "type": "boolean",
      "env": null,
      "display": "--json",
      "description": "Output raw JSON instead of a table",
    },
    {
      "name": "--no-color",
      "alias": null,
      "type": "boolean",
      "env": null,
      "display": "--no-color",
      "description": "Disable colored output",
    },
    {
      "name": "--version",
      "alias": "-v",
      "type": "boolean",
      "env": null,
      "display": "-v, --version",
      "description": "Print the CLI version",
    },
    {
      "name": "--help",
      "alias": "-h",
      "type": "boolean",
      "env": null,
      "display": "-h, --help",
      "description": "Show help for any command",
    },
  ],
  "examples": [
    "w6w me",
    "w6w workflows list",
    "w6w workflows run wf_01H… --wait",
    "w6w documents list",
    "w6w vars create greeting --type string --value hello",
    'w6w run conn_01H… --action send_email --payload \'{"to":"a@b.com"}\'',
  ],
};

/** Every command path the parser may match, aliases included. */
export const COMMAND_PATHS: string[][] = [
  [
    "me",
  ],
  [
    "info",
  ],
  [
    "run",
  ],
  [
    "connections",
    "list",
  ],
  [
    "workflows",
    "list",
  ],
  [
    "workflows",
    "run",
  ],
  [
    "documents",
    "list",
  ],
  [
    "documents",
    "get",
  ],
  [
    "documents",
    "get-by-key",
  ],
  [
    "documents",
    "create",
  ],
  [
    "documents",
    "update",
  ],
  [
    "documents",
    "delete",
  ],
  [
    "vars",
    "list",
  ],
  [
    "vars",
    "get",
  ],
  [
    "vars",
    "get-by-name",
  ],
  [
    "vars",
    "create",
  ],
  [
    "vars",
    "update",
  ],
  [
    "vars",
    "delete",
  ],
  [
    "functions",
    "run",
  ],
  [
    "endpoints",
    "run",
  ],
];

/** The exit-code contract, verbatim from the shared contract's `cli.exitCodes`. */
export const EXIT_CODES: HelpExitCode[] = [
  {
    "code": 0,
    "name": "SUCCESS",
    "meaning": "success, including help and a queued/running workflow",
  },
  {
    "code": 1,
    "name": "USAGE",
    "meaning": "usage error",
  },
  {
    "code": 2,
    "name": "API_ERROR",
    "meaning": "API error (4xx/5xx, including auth failure)",
  },
  {
    "code": 3,
    "name": "RUN_FAILURE",
    "meaning": "run failure (--wait returned status 'failed')",
  },
];

export const EXIT_SUCCESS: number = 0;
export const EXIT_USAGE: number = 1;
export const EXIT_API_ERROR: number = 2;
export const EXIT_RUN_FAILURE: number = 3;

/** The global flags, lifted out of the tree for the argument parser. */
export const GLOBAL_FLAGS: HelpGlobalFlag[] = HELP_TREE.globalFlags;
